from __future__ import annotations

from typing import List

from gpvb.models import Finding, PageResult

from .autogenerated_content import apply_autogenerated_findings, detect_autogenerated_findings
from .context import ProgramPolicyContext, build_context
from .deceptive_representation import detect_deceptive_representation
from .invalid_traffic_signals import detect_invalid_traffic_signals
from .malware_risk import detect_malware_risk
from .manipulative_ad_placement import detect_manipulative_ad_placement
from .risk import calculate_account_risk_score
from .traffic_source_abuse import detect_traffic_source_abuse
from .ugc_risk import detect_ugc_risk


def run_program_policy_detectors(page: PageResult, context: ProgramPolicyContext) -> List[Finding]:
    findings: List[Finding] = []
    findings.extend(detect_invalid_traffic_signals(page, context))
    findings.extend(detect_manipulative_ad_placement(page, context))
    findings.extend(detect_deceptive_representation(page))
    findings.extend(detect_malware_risk(page, context))
    findings.extend(detect_traffic_source_abuse(page))
    findings.extend(detect_ugc_risk(page))
    findings.extend(detect_autogenerated_findings(page))
    return findings


__all__ = [
    "ProgramPolicyContext",
    "build_context",
    "run_program_policy_detectors",
    "apply_autogenerated_findings",
    "detect_autogenerated_findings",
    "calculate_account_risk_score",
]
