from pathlib import Path

from gpvb.detect.program_policy.autogenerated_content import apply_autogenerated_findings
from gpvb.detect.program_policy.context import LabelBlock, ProgramPolicyContext, TextBlock
from gpvb.detect.program_policy.deceptive_representation import detect_deceptive_representation
from gpvb.detect.program_policy.malware_risk import detect_malware_risk
from gpvb.detect.program_policy.manipulative_ad_placement import detect_manipulative_ad_placement
from gpvb.detect.program_policy.traffic_source_abuse import detect_traffic_source_abuse
from gpvb.detect.text import extract_visible_text
from gpvb.models import AdElement, PageResult, Severity


def _load_fixture(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")


def _make_page(html: str, url: str = "https://example.com") -> PageResult:
    return PageResult(
        url=url,
        final_url=url,
        status=200,
        html=html,
        text=extract_visible_text(html),
    )


def test_incentivized_click_fixture_triggers_critical():
    html = _load_fixture("tests/fixtures/incentivized_click.html")
    page = _make_page(html)
    findings = detect_traffic_source_abuse(page)
    assert any(finding.severity == Severity.critical for finding in findings)


def test_fake_navigation_ads_fixture_triggers_manipulative():
    html = _load_fixture("tests/fixtures/fake_navigation_ads.html")
    page = _make_page(html)
    page.ad_elements.append(
        AdElement(selector="ins.adsbygoogle", x=0, y=20, width=300, height=100, overlaps_nav=True)
    )
    context = ProgramPolicyContext(
        text_blocks=[TextBlock(text="Home", x=0, y=10, width=50, height=10)],
        label_blocks=[],
        viewport={"width": 1366, "height": 768},
    )
    findings = detect_manipulative_ad_placement(page, context)
    assert any(finding.detector == "manipulative_ad_styling" for finding in findings)


def test_deceptive_affiliation_fixture_triggers_high():
    html = _load_fixture("tests/fixtures/deceptive_affiliation.html")
    page = _make_page(html)
    findings = detect_deceptive_representation(page)
    assert any(finding.severity == Severity.high for finding in findings)


def test_forced_download_fixture_triggers_critical():
    html = _load_fixture("tests/fixtures/forced_download.html")
    page = _make_page(html)
    page.ad_elements.append(AdElement(selector="ins.adsbygoogle", x=0, y=20, width=300, height=100))
    context = ProgramPolicyContext(
        text_blocks=[TextBlock(text="Download now", x=0, y=30, width=120, height=10)],
        label_blocks=[LabelBlock(text="Advertisement", x=0, y=0, width=80, height=10, font_size=12, opacity=1)],
        viewport={"width": 1366, "height": 768},
    )
    findings = detect_malware_risk(page, context)
    assert any(finding.severity == Severity.critical for finding in findings)


def test_autogenerated_cluster_fixture_triggers_high():
    html_a = _load_fixture("tests/fixtures/autogenerated_cluster/page1.html")
    html_b = _load_fixture("tests/fixtures/autogenerated_cluster/page2.html")
    page_a = _make_page(html_a, url="https://example.com/a")
    page_b = _make_page(html_b, url="https://example.com/b")
    apply_autogenerated_findings([page_a, page_b], threshold=0.8)
    assert any(finding.severity == Severity.high for finding in page_a.findings + page_b.findings)
